development:
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: mudanca_development
  username: #{ENV['DB_USER_NAME']}

test:
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: mudanca_test
  username: #{ENV['DB_USER_NAME']}

production:
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: mudanca_production
  username: #{ENV['DB_USER_NAME'}]